### Chi-squared test for goodness of fit

In [23]:
import numpy as np
from scipy.stats import chi2, chisquare

In [1]:
obs_brown = 86
obs_albino = 14

exp_brown = 75
exp_albino = 25

In [3]:
obs_brown + obs_albino, exp_albino + exp_brown

(100, 100)

In [25]:
chi2_stat, p_value = chisquare((obs_brown,obs_albino), (exp_brown, exp_albino))
chi2_stat, p_value

(6.453333333333333, 0.011074437676156615)

In [52]:
def chi_square(observed, expected):
    return np.sum([(obs - exp)**2 / exp for obs,exp in zip(observed, expected)])
    

In [19]:
by_hand_chi_stat = chi_square((obs_brown,obs_albino), (exp_brown, exp_albino))
by_hand_chi_stat

6.453333333333333

In [20]:
by_hand_chi_stat == chi2_stat

True

In [18]:
df = len((obs_brown,obs_albino)) - 1

In [26]:
by_hand_chi_pval =  chi2.sf(by_hand_chi_stat, df)
by_hand_chi_pval

0.011074437676156615

In [27]:
by_hand_chi_pval == p_value

True

-----

In [62]:
import numpy as np
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [47]:
site = ['rockhampton','bowen','mackay']
infected = [12,7,14]
uninfected = [8,13,6]

In [48]:
row_total = np.array([infected,uninfected]).sum(1)
col_total = np.array([infected,uninfected]).sum(0)


if np.sum(row_total) == np.sum(col_total):
    grand_total = np.sum(row_total)
    print(row_total, col_total, grand_total)

[33 27] [20 20 20] 60


In [53]:
# np.outer(row_total, col_total) calculates the outer product of the row totals and column totals.
# Dividing by grand_total gives you the expected values for each cell.


expected_vals= np.outer(row_total, col_total) / grand_total
print("Expected Values:\n", expected_vals)

Expected Values:
 [[11. 11. 11.]
 [ 9.  9.  9.]]


In [50]:
contingency_table = np.array([infected, uninfected])
contingency_table

array([[12,  7, 14],
       [ 8, 13,  6]])

In [51]:
# Perform the Chi-Square test of independence
chi2, p, dof, expected = chi2_contingency(contingency_table)
chi2, p, dof, expected

(5.252525252525253,
 0.07234835041290566,
 2,
 array([[11., 11., 11.],
        [ 9.,  9.,  9.]]))

In [59]:
## reshape values to have them as 1D, and use the previously written function
by_hand_indep_chi2 = chi_square(contingency_table.reshape(-1),  expected_vals.reshape(-1))
by_hand_indep_chi2

5.252525252525253

In [75]:
df = (contingency_table.shape[0] -1) * (contingency_table.shape[1] -1) 
df

2

In [76]:
by_hand_chi_independent_pval =  chi2.sf(by_hand_indep_chi2, df)
by_hand_chi_independent_pval

0.07234835041290566